---
- name: cheflab-server
  box: bento/ubuntu-14.04
  ram: 1512
  ip: 192.168.38.31
  share: true
  default_share: true
  share_keys: false
  cheflab_shared_conf: "conf"
- name: cheflab-workstation
  box: bento/ubuntu-14.04
  ram: 512
  ip: 192.168.38.32
  share: true
  default_share: true
  cookbooks: "~/Google Drive/Personal/Chef"
  cookbook_share: false
  share_keys: false
  cheflab_shared_conf: "conf"
